global:
  smtp_from: alerts@securenet.com
  smtp_smarthost: localhost:587
receivers:
- email_configs:
  - body: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
    subject: 'SecureNet Alert: {{ .GroupLabels.alertname }}'
    to: ops-team@securenet.com
  name: web.hook
  webhook_configs:
  - send_resolved: true
    url: http://alertmanager-webhook:5000/alerts
route:
  group_by:
  - alertname
  group_interval: 10s
  group_wait: 10s
  receiver: web.hook
  repeat_interval: 1h
