scrape_configs:
- job_name: securenet-api
  metrics_path: /api/metrics
  scrape_interval: 30s
  static_configs:
  - targets:
    - securenet-api:8000
- job_name: kubernetes-pods
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - action: keep
    regex: true
    source_labels:
    - __meta_kubernetes_pod_annotation_prometheus_io_scrape
- job_name: node-exporter
  scrape_interval: 15s
  static_configs:
  - targets:
    - node-exporter:9100
