components:
  schemas:
    AuthResponse:
      properties:
        access_token:
          type: string
        expires_in:
          type: integer
        token_type:
          type: string
        user:
          $ref: '#/components/schemas/User'
      type: object
    User:
      properties:
        created_at:
          format: date-time
          type: string
        email:
          type: string
        id:
          type: integer
        role:
          type: string
        username:
          type: string
      type: object
  securitySchemes:
    BearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
info:
  contact:
    email: api-support@securenet.com
    name: SecureNet API Support
    url: https://docs.securenet.com
  description: Comprehensive API for SecureNet cybersecurity platform
  title: SecureNet Enterprise API
  version: 2.0.0
openapi: 3.0.0
paths: {}
servers:
- description: Production
  url: https://api.securenet.com/v2
- description: Staging
  url: https://staging-api.securenet.com/v2
